### ISSUE TITLE
Pipenv run report displays the coverage of imported python modules

### ISSUE THREAD

**Issue by Daholli** [jomazi/Python-Default#4]
Not quite sure if that is the intended behavior. I was looking to limit the code coverage report to only encompass the actual files of the project but havent found a way to do that. 

One possible reason for that might be that the first pipenv was not installed to .venv but to .local

![2020-12-19-204312_2880x1620_scrot](https://user-images.githubusercontent.com/25060097/102698055-fde34b00-423a-11eb-8522-56f01a402806.png)

is there a way to limit coverage to only only user files from ./src/ and ./tests/

**Comment by chbridges** [comment]
Open Pipfile and search for this line:
test = "coverage run -m unittest discover -s ./tests -p *_test.py"

Replace it with:
test = "coverage run --include=src/*,test/* -m unittest discover -s ./tests -p *_test.py"

**Comment by chbridges** [comment]
Open Pipfile and search for this line:
test = "coverage run -m unittest discover -s ./tests -p *_test.py"

Replace it with:
test = "coverage run --include=src/\*,tests/\* -m unittest discover -s ./tests -p *_test.py"

**Comment by Daholli** [comment]
```
pipenv run coverage run --include=src/*,tests/* -m unittest ./tests/preprocessing_test.py
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.9/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib/python3.9/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/lib/python3.9/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.9/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ValueError: Empty module name
Coverage.py warning: No data was collected. (no-data-collected)
```

I did find that when reading the documentation but sadly this feature does not seem to work for me

**Comment by Daholli** [comment]
nvm i found out that was an error with my shell 
for zsh i had to add 
```unsetopt nomatch``` to my .zshrc

now everything works like a charm :) thx a lot
